name: saptest-helm-manually
image: bsmhdevteam/saptest:v1
deployment:
  replicas: 4
  strategy: RollingUpdate
  imagePullPolicy: IfNotPresent
  targetPort: 1234
  containerPort: 5678
  restartPolicy: Always
  nodeSelectorOs: linux

service:
  type: NodePort