apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
  ports:
  - name: {{ .Values.deployment.containerPort | quote }}
    port: {{ .Values.deployment.containerPort }}
    targetPort: {{ .Values.deployment.targetPort }}
status:
  loadBalancer: {}
